### ISSUE TITLE
Profiling data directory

### ISSUE THREAD

**Issue by jayvdb** [manahl/pytest-plugins#83]
The profile output directory is hard-coded to `prof/`.  It should be configurable.

**Comment by RaiVaibhav** [comment]
pytest have its own plugin hook `pytest_addoption` and I don't think explicitly `click` will be needed and right now `pytest-profiling` rely on the plugin hook IMO.

**Comment by chaoflow** [comment]
@RaiVaibhav ``pytest_addoption`` is used to extend pytest's CLI. The use case I'm referring to is using pytest to test a CLI program that uses click.

In order to work with tests that change the working directory, the profile output directory needs to be turned absolute upon startup, not during test execution, independent of whether configurable or not.
